---
- hosts: all
  sudo: true
  tasks:

  - name: create /var/www
    file: path=/var/www state=directory

  - name: create site symlink
    file: src=/vagrant dest=/var/www/site state=link
    notify: restart apache

  - name: install misc packages
    apt: name={{ item }} state=latest
    with_items:
      - ruby-dev
      - git-core
      - curl
      - unzip
      - vim

  - name: install language packs for locale support
    apt: name={{ item }} state=latest
    with_items:
      - language-pack-it-base

  # Apache2 

  - name: ensure apache is installed
    apt: name=apache2 state=present

  - name: make sure apache is running
    action: service name=apache2 state=started enabled=true

  - file: src=/etc/apache2/mods-available/rewrite.load dest=/etc/apache2/mods-enabled/rewrite.load state=link
    notify: restart apache

  - file: src=/etc/apache2/mods-available/headers.load dest=/etc/apache2/mods-enabled/headers.load state=link
    notify: restart apache

  - copy: src=/vagrant/ansible/templates/site.conf dest=/etc/apache2/sites-enabled/site.conf
    notify: restart apache

  - file: path=/etc/apache2/sites-enabled/000-default.conf state=absent
    notify: restart apache

  - file: path=/etc/apache2/conf.d state=directory

  - copy: src=/vagrant/ansible/templates/fqdn.conf dest=/etc/apache2/conf.d/fqdn.conf
    notify: restart apache

  - copy: src=/vagrant/ansible/templates/nosendfile.conf dest=/etc/apache2/conf.d/nosendfile.conf
    notify: restart apache

  # MySQL

  - name: install MySQL
    apt: name={{ item }} state=latest
    with_items:
      - mysql-server
      - mysql-client
      - python-mysqldb

  - name: add mysql user
    mysql_user: name=vagrant
                host={{ item }}
                password=vagrant priv=*.*:ALL,GRANT
                login_user=root
                login_password=
    with_items:
      - '%'
      - localhost

  - name: create mysql databases
    mysql_db: name={{ item }}
              state=present
              encoding=utf8
              collation=utf8_unicode_ci
    with_items:
      - todolist
      
  # Copy database dump file to remote host and restore it to database 'my_db'
  - copy: src=/vagrant/ansible/templates/todolist.sql dest=/tmp
  - mysql_db: name=todolist state=import target=/tmp/todolist.sql

  
  - file: path=/etc/mysql/conf.d state=directory
  - name: Set MySQL number of connections
    copy: src=/vagrant/ansible/templates/max_connections.cnf dest=/etc/mysql/conf.d/max_connections.cnf
    notify: restart mysql
  - name: Install mysql command line client configuration file
    copy: src=/vagrant/ansible/templates/my.cnf dest=/home/vagrant/.my.cnf owner=vagrant group=vagrant

  # PHP
  
  - name: install PHP5 packages
    apt: name={{ item }} state=latest
    with_items:
      - php5
      - libapache2-mod-php5     
      - php5-apcu     
      - php5-cli      
      - php5-common   
      - php5-curl     
      - php5-fpm      
      - php5-gd       
      - php5-json     
      - php5-mcrypt
      - php5-mysqlnd
      - php5-readline 
      - php5-xdebug   

  - file: path=/etc/php5/conf.d state=directory

  - copy: src=/vagrant/ansible/templates/php-site.ini dest=/etc/php5/conf.d/php-site.ini
    notify: restart apache

  - name: symlink common php configuration for cli handler
    file: src=/etc/php5/conf.d/php-site.ini dest=/etc/php5/cli/conf.d/php-site.ini state=link
    notify: restart apache

  - name: symlink common php configuration for apache2 handler
    file: src=/etc/php5/conf.d/php-site.ini dest=/etc/php5/apache2/conf.d/php-site.ini state=link
    notify: restart apache

  # phpmyadmin

  - name: install phpmyadmin
    apt: name=phpmyadmin state=latest
    
  - name: ensure that phpmyadmin's stock config is deleted
    file: path=/etc/apache2/conf.d/phpmyadmin.conf state=absent
  
  # Compass

  - name: add nodejs ppa
    apt_repository: repo='ppa:chris-lea/node.js'

  - name: install nodejs
    apt: name=nodejs state=latest

  - name: install compass
    command: gem install compass sass chunky_png fssm creates=/usr/local/bin/compass

  # Set up site

  - file: src=/vagrant dest=/var/www/site state=link
  - file: path={{ item }} owner=vagrant group=vagrant mode=0777 state=directory
    with_items:
      - /var/cache/site
      - /var/cache/site/cache
      - /var/cache/site/clockwork
      - /var/cache/site/logs
      - /var/cache/site/meta
      - /var/cache/site/sessions
      - /var/cache/site/views

  # Handlers

  handlers:
    - name: restart apache
      action: service name=apache2 state=restarted
    - name: restart mysql
      action: service name=mysql state=restarted
